databases:
  - name: kyrgyz-data-db
    plan: free

services:
  - type: web
    name: kyrgyz-data-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kyrgyz-data-db
          property: connectionString
      - key: API_KEY
        generateValue: true
      - key: RATE_LIMIT_PER_MIN
        value: 60
      - key: DATA_URL
        value: https://files.catbox.moe/d1ktyc.txt
